name = "HierarchicalLogging"
uuid = "f33c120b-91a0-4a1c-b926-14fa61c08c77"
authors = ["Curt Da Silva <curt.dasilva@gmail.com>"]
version = "1.0.1"

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingCommon = "44db15ec-78df-42c5-8c4e-36d253f36098"

[compat]
Dictionaries = "0.3, 0.4"
Logging = "1"
LoggingCommon = "1.0.1"
julia = "1.6"